spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgres://root_yz7i_user:vLN98sKp3kyIAp8A12lt4PAi5dsHBivr@dpg-ckuuti6b0mos73di54qg-a.oregon-postgres.render.com/root_yz7i
    password: vLN98sKp3kyIAp8A12lt4PAi5dsHBivr
    username: root_yz7i_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

    #server.port=8081
    #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    #spring.datasource.url=jdbc:mysql://localhost:3306/JWT?createDatabaseIfNotExist=true
    #spring.datasource.username=root
    #spring.datasource.password=#navya143##
    #spring.jpa.hibernate.ddl-auto=update
    #spring.jpa.show-sql=true
    #spring.application.name=JWT